license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="hatchery_logo.png"
authors="afjan"
description='''Spawners can be mined: they drop a Broken Spawner. Mobs killed by players rarely drop their
spawn egg (0.5%), and a spawn egg brings a Broken Spawner back to life as a spawner of that mob.'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
