package com.afjan.arsenal.client;

import java.util.Map;

import com.afjan.arsenal.gun.GunType;

import net.minecraft.world.phys.Vec3;

/**
 * Where each gun's muzzle is, measured on its 3D model. GENERATED by tools/gun_models.py (gen_data.py writes it):
 * edit the models there, not this file.
 */
public final class GunViewmodels {
    /**
     * @param firstPerson in first-person view space (blocks; x right, y up, -z forward) for the right hand
     * @param fromShoulder third person, from the right shoulder pivot with the head level (player space: x left,
     *                     y up, z forward)
     */
    public record Muzzle(Vec3 firstPerson, Vec3 fromShoulder) {}

    /** The right shoulder pivot in player space (feet at the origin, facing +z). */
    public static final Vec3 SHOULDER = new Vec3(-0.2930, 1.2900, -0.0000);

    public static final Map<GunType, Muzzle> MUZZLES = Map.ofEntries(
            Map.entry(GunType.AK47, new Muzzle(new Vec3(0.4226, -0.2963, -1.8650), new Vec3(0.1198, 0.1674, 1.4652))),
            Map.entry(GunType.M4A1, new Muzzle(new Vec3(0.4283, -0.3198, -1.7565), new Vec3(0.1197, 0.1546, 1.4184))),
            Map.entry(GunType.SCAR_H, new Muzzle(new Vec3(0.4221, -0.2776, -1.8736), new Vec3(0.1198, 0.1800, 1.4711))),
            Map.entry(GunType.AUG, new Muzzle(new Vec3(0.3897, -0.2863, -1.7374), new Vec3(0.1197, 0.1512, 1.0742))),
            Map.entry(GunType.GLOCK17, new Muzzle(new Vec3(0.3397, -0.2044, -1.3591), new Vec3(0.1198, 0.1448, 0.8084))),
            Map.entry(GunType.M1911, new Muzzle(new Vec3(0.3362, -0.1955, -1.4260), new Vec3(0.1197, 0.1535, 0.8486))),
            Map.entry(GunType.M9, new Muzzle(new Vec3(0.3363, -0.2001, -1.4230), new Vec3(0.1198, 0.1560, 0.8596))),
            Map.entry(GunType.DEAGLE, new Muzzle(new Vec3(0.3266, -0.1287, -1.6085), new Vec3(0.1198, 0.1766, 0.9118))),
            Map.entry(GunType.BARRETT, new Muzzle(new Vec3(0.3977, -0.2192, -2.3394), new Vec3(0.1197, 0.2448, 1.9749))),
            Map.entry(GunType.SVD, new Muzzle(new Vec3(0.3969, -0.2818, -2.3549), new Vec3(0.1198, 0.1754, 1.7772))),
            Map.entry(GunType.AWP, new Muzzle(new Vec3(0.3991, -0.2654, -2.3134), new Vec3(0.1197, 0.1870, 1.7566))),
            Map.entry(GunType.REMINGTON870, new Muzzle(new Vec3(0.4170, -0.3770, -1.9722), new Vec3(0.1197, 0.1130, 1.5341))),
            Map.entry(GunType.SPAS12, new Muzzle(new Vec3(0.4269, -0.2598, -1.7830), new Vec3(0.1197, 0.2134, 1.5424))),
            Map.entry(GunType.AA12, new Muzzle(new Vec3(0.4172, -0.2423, -1.9678), new Vec3(0.1198, 0.2024, 1.5256))),
            Map.entry(GunType.SAWED_OFF, new Muzzle(new Vec3(0.4385, -0.3121, -1.5621), new Vec3(0.1198, 0.1146, 1.0766))),
            Map.entry(GunType.RPG7, new Muzzle(new Vec3(0.4288, -0.2327, -1.3054), new Vec3(0.1198, 0.1660, 1.0927))),
            Map.entry(GunType.M32, new Muzzle(new Vec3(0.4149, -0.1836, -1.5721), new Vec3(0.1198, 0.1986, 1.2695))),
            Map.entry(GunType.RAILGUN, new Muzzle(new Vec3(0.4118, -0.2309, -2.0723), new Vec3(0.1197, 0.2094, 1.5918))));

    private GunViewmodels() {}
}
